name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: zsh setup
      - run: sudo apt install zsh
      - uses: actions/checkout@v3
      - run: |
          zsh ./scripts/installer.zsh
